name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: update apt cache
      run: sudo apt-get update && false
    - name: install prerequisites
      run: sudo apt-get install -y libboost-all-dev
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: make test setup
      run: sudo make test-setup
    - name: run tests
      run: make test
